export const LOAD_MAP_OF_VN_START = 'LOAD_MAP_OF_VN_START';
export const LOAD_PROVINCES_CARD_START = 'LOAD_PROVINCES_CARD_START';
export const LOAD_PROVINCES_CARD_SUCCESS = 'LOAD_PROVINCES_CARD_SUCCESS';
export const LOAD_PROVINCES_CARD_FAILED = 'LOAD_PROVINCES_CARD_FAILED';
export const LOAD_DISTRICTS_DATA_START = 'LOAD_DISTRICTS_DATA_START'; 
export const LOAD_DISTRICTS_DATA_SUCCESS = 'LOAD_DISTRICTS_DATA_SUCCESS';
export const LOAD_DISTRICTS_DATA_FAILED = 'LOAD_DISTRICTS_DATA_FAILED'; 